### ISSUE TITLE
Api reference

### ISSUE THREAD

**Issue by kzolti** [protocolbuffers/protobuf-javascript#107]
I would like to ask how useful the old reference is.
https://web.archive.org/web/20220422095626/https://developers.google.com/protocol-buffers/docs/reference/javascript-generated

**Comment by dibenede** [comment]
It should be fairly up to date; I'm not actively aware of any differences. Separately, we have revived the docs here: https://github.com/protocolbuffers/protobuf-javascript/blob/main/docs/index.md . I think the only differences are fixed links and tweaked protoc commands.
