### ISSUE TITLE
Could you make your npm version up to date?

### ISSUE THREAD

**Issue by start940315** [protocolbuffers/protobuf-javascript#155]
I found that your npm version google-protobuf.js is not up to date? Could you please consider renew it? That would be a great help!

**Comment by start940315** [comment]
> I'm not clear on what you're referring to. 3.21.2 is the latest version (published Oct 10, 2022).
> 
> Are you referring to the version compared to the main protobuf repo (https://github.com/protocolbuffers/protobuf)? If so, we use a separate versioning system.

So what's the main protobuf repo version? I DO need this version!

**Comment by start940315** [comment]
> I'm not clear on what you're referring to. 3.21.2 is the latest version (published Oct 10, 2022).
> 
> Are you referring to the version compared to the main protobuf repo (https://github.com/protocolbuffers/protobuf)? If so, we use a separate versioning system.

And I mean the npm version's code is different with the code I generated from this repo. And I think my code is the latest one. So do you mind to update your npm code?

**Comment by dibenede** [comment]
What revision are you compiling protobuf-javascript at? If it's HEAD, we have blocking issues preventing us from shipping the commits since the 3.21.2 release.

**Comment by start940315** [comment]
At last we forked this repo and compile HEAD with `protoc@3.20.3`. it works in our env. But after I check the generated code, I know it is still not robust. Because the way to find the global instance may cause error. And the code below generated by `protoc@3.21.9` is correct.
```javascript
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();
```

**Comment by lukesandberg** [comment]
Is it possible that you have changed how you invoke the code generator and are accidentally no longer setting `import_style= commonjs_strict` ?

**Comment by start940315** [comment]
> _strict

Actually we use `import_style= commonjs`. After I change it to `import_style= commonjs_strict`, it removes global with a plain object. I didn't test it because I have solved my problem. This issue could be closed.
