### ISSUE TITLE
What's the difference between protobuf-javascript and protobuf.js

### ISSUE THREAD

**Issue by cuixiping** [protocolbuffers/protobuf-javascript#157]
What's the difference between them

[protobuf-javascript](https://github.com/protocolbuffers/protobuf-javascript)
[protobuf.js](https://github.com/protobufjs/protobuf.js)

**Comment by dibenede** [comment]
They are different implementations of protobuf in javascript. Both support the binary proto wire format. The projects have no relation to one another otherwise.

We are not particularly familiar with the protobuf.js and can't say much about differences between the APIs.
