### ISSUE TITLE
[jstype = JS_STRING] Is not supported properly for big (64 bit) numbers.

### ISSUE THREAD

**Issue by nbabanov** [protocolbuffers/protobuf-javascript#159]
This function is totally incompatible with `[jstype = JS_STRING]` this approach on `uint64`.

The function receives a strings and tries to do number manipulations on it... For the same reason BigInt is also not supported.

```
jspb.BinaryEncoder.prototype.writeUnsignedVarint64 = function(value) {
  jspb.asserts.assert(value == Math.floor(value));
  jspb.asserts.assert(
      (value >= 0) && (value < jspb.BinaryConstants.TWO_TO_64));
  jspb.utils.splitInt64(value);
  this.writeSplitVarint64(jspb.utils.getSplit64Low(), jspb.utils.getSplit64High());
};
```

**Comment by dibenede** [comment]
This falls under the general umbrella of fixing 64-bit int support (#67)
