### ISSUE TITLE
Kokoro job for continuous benchmarks is broken on master by recent JS changes

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf-javascript#16]
This is the first failing build:
https://source.cloud.google.com/results/invocations/7416b136-a366-472c-ad3b-0890c6fb9493/targets (from Jun 2 2021)

The rootcause is probably this PR:
https://github.com/protocolbuffers/protobuf/pull/8610 (it was green before and started failing right after it got merged).

@kjin @TeBoring  can you please help fixing this?

**Comment by dibenede** [comment]
This is obsolete and we are working on getting Kokoro up and running for this new repo.
