### ISSUE TITLE
Add root level export for wrappers_pb

### ISSUE THREAD

**Issue by steven-supersolid** [protocolbuffers/protobuf-javascript#197]
To access the wrappers objects a client must do the following:

```
const jspbWrappers = require('google-protobuf/google/protobuf/wrappers_pb');
```

This requires knowledge of the internal structure of the package. Instead a client should be able to do something like

```
const jspbWrappers = require('google-protobuf').jspbWrappers
```
---

Due to our limited support resources, feature requests will generally not be accepted, except for those referring to build or tooling integration.

**Comment by dibenede** [comment]
Sorry for the delay. I think I understand where this sentiment is coming from, but I think the path to package approach is typical across protobuf languages.
