### ISSUE TITLE
When is the documentation planned to be published?

### ISSUE THREAD

**Issue by ericmorand** [protocolbuffers/protobuf-javascript#220]
Hey team,

We are currently challenging a few protobuf JavaScript and TypeScript libraries and it seems like yours does not have any documentation published.

We are assuming that, considering that the project has started 8 years ago, there is no plan to publish a documentation, but in case we are wrong: when can we expect it to be published?

**Comment by dibenede** [comment]
There's some documentation in the README, but the bulk of it is here: https://github.com/protocolbuffers/protobuf-javascript/blob/main/docs/index.md .

**Comment by ericmorand** [comment]
Thank you @dibenede. Can we assume that there is no JavaScript API (to create a namespace, create a message...), or is it not documented yet?

**Comment by dibenede** [comment]
Sorry, I'm not clear on what you're looking for when you say "to create a namespace, create a message...".

We'll generate a JS API for whatever protobuf files you provide. We do not support reflection/DynamicMessage (something like [this](https://protobuf.dev/reference/cpp/api-docs/google.protobuf.dynamic_message/) in C++).
