### ISSUE TITLE
BigInt for 64-bit integers

### ISSUE THREAD

**Issue by seishun** [protocolbuffers/protobuf-javascript#34]
**What language does this apply to?**
JavaScript

**Describe the problem you are trying to solve.**
Getting and setting 64-bit integers without losing precision.

**Describe the solution you'd like**
Use BigInt to represent 64-bit integers.

**Describe alternatives you've considered**
Using strings, but:
* This requires modifying .proto files, see https://github.com/protocolbuffers/protobuf/pull/6504.
* It's inconvenient if you need to do any operations on the value.

**Additional context**
There's a `binary` protoc option that enables serialization into Uint8Array. I suggest adding a `bigint` option that makes getters for 64-bit integer fields return BigInt and preferably requires BigInt in setters.

**Comment by KiyonamiYu** [comment]
I have encountered the same problem..
Is there any way to solve it now..🤧

**Comment by KiyonamiYu** [comment]
In `xx.proto`: `int64 value`;
In `xx_pb.d.ts`: `setValue(value: number)`;
When I pass BigInt to `setValue`, I will get a TypeError: Cannot convert a BigInt value to a number.

**Comment by dibenede** [comment]
We understand this is a problem. We cannot support bigint due to browser support horizons. Long term, we plan to support 64 bit ints another way.
