### ISSUE TITLE
The generated code(js) is different from what I defined in .proto file

### ISSUE THREAD

**Issue by microlv** [protocolbuffers/protobuf-javascript#37]
**What version of protobuf and what language are you using?**
Version: v3.11.0
Language: Javascript

**What operating system (Linux, Windows, ...) and version?**
Windows/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
protoc

**What did you do?**
1. download the [protoc cmder](https://github.com/protocolbuffers/protobuf/releases/download/v3.11.0/protoc-3.11.0-win64.zip)
2.define the .proto file liek the below code:
```js
syntax = "proto3";

message Response {
	string result = 1;
	repeated string data = 2;
	repeated string dataEChart = 3;
	string con_lv = 4;
	string Msg = 5;
}

```
3. protoc  --js_out=import_style=commonjs,binary:. *.proto
4. look into the _pb.js file
```js
proto.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    result: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dataList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    dataechartList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    conLv: jspb.Message.getFieldWithDefault(msg, 4, ""),
    msg: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}
```
 

**What did you expect to see**
I want to keep my field as the same as I defined in .proto file. but I found some fields are changed.
In toObject function there are some fields are changed, like:
```js
repeated string data = 2; ===>> dataList //why has List???
repeated string dataEChart = 3; ===>>dataechartList  //why to LowerCase, why has List???
string con_lv = 4; ===>> conLv //why changed to Lv??
string Msg = 5; ===>> msg //why lowercase
```

**What did you see instead?**
**My field has been changed! and I want to keep it as the same as I defined it in .proto file**

**Anything else we should know about your project / environment**
web project/ commonjs coding style/ use webpack/

**Comment by dibenede** [comment]
We transform names to lower camelcase intentionally to match commonjs style as opposed to the lower_style that is more common in protobuf. Additionally, we add suffixes to match the types. We can't easily change this because it would be a compatibility break.
