### ISSUE TITLE
Option to force singular field naming (JS generator)

### ISSUE THREAD

**Issue by 4nte** [protocolbuffers/protobuf-javascript#42]
**What language does this apply to?**
This is for proto3 Javascript code generation. 

**Describe the problem you are trying to solve.**
A repeated field, when generated to javascript, will be appended with a _List_ suffix. This behaviour introduces (forced) changes to the user-defined names which can sometimes be unwanted as we'd (generally) expect the field names to match the original proto file.

**Describe the solution you'd like**
Field annotation (a boolean) to force singular naming.

**Describe alternatives you've considered**
1. Writing a custom mapper to rename the fields to their original proto name.
2. Modifying generated JS code.

**Additional context**
https://stackoverflow.com/questions/51508553/why-does-the-protobuf-javascript-compiler-suffix-collections-with-list-map

**Comment by SmashPlusUltra** [comment]
It'll be nice to see the opinion of the developers which maintain the project about this issue.

**Comment by dibenede** [comment]
Sorry we have no plans to change the naming conventions or adding options to control the naming due to compatibility and maintenance issues, respectively.

**Comment by jpgundrum** [comment]
Hey, I just wanted to update this thread as I have just recently dealt with this very issue. There is a forked repository which can be found [here](https://github.com/surfingtomchen/protobuf-javascript) that removes the auto addition of "List" when the "repeated" keyword is used in the proto document. 

After building the binary (protoc-gen-js in this case) from the cloned repository you can run the cmd `protoc --plugin=protoc-gen-js=./protoc-gen-js --js_out=import_style=commonjs,binary:. my_proto_file.proto` which will generate a .js file that does not auto append "List".
