### ISSUE TITLE
error on goog.require jspb.* dependencies

### ISSUE THREAD

**Issue by dasDaniel** [protocolbuffers/protobuf-javascript#48]
the generator generates a js file from the proto file

in it there are the following lines 
```js
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.rpc.Status');
```

I've been trying to figure out how to provide these dependencies.

after a day of struggling with it, I've only been able to use it only by including `var jspb = require('google-protobuf');` inside the generated file and commenting out all the `goog.require` lines. This may not solve the `proto.google.rpc.Status` dependency, but looks like I'm able to at least use (require) my generated js file without getting errors.

I've seen this/similar issues mentioned but without a clear path to resolving it.

the documentation mentions: 
>  The generated code will also goog.require() many types in the core library, and they will require many types in the Google Closure library. So make sure that your goog.provide() / goog.require() setup can find all of your generated code, the core library .js files in this directory, and the Google Closure library itself.

but there is no detail regarding how to goog.provide the jspb dependency

**Comment by dibenede** [comment]
Did this suggestion work?

> For not using closure library, you may use commonjs option to generate the files. e.g.
> 
> ```
>  protoc --js_out=import_style=commonjs:. Foo.proto
> ```

**Comment by dasDaniel** [comment]
I don't know. I haven't touched the project and don't have access to it so I can't  check or reproduce anymore. So for my intents and purposes, this can be closed.
