### ISSUE TITLE
[JavaScript] Add insertion points to the compiler

### ISSUE THREAD

**Issue by travikk** [protocolbuffers/protobuf-javascript#50]
**What language does this apply to?**
This feature request is for proto3 and JavaScript language generator.

**Describe the problem you are trying to solve.**

Problem I am trying to solve, is that when using gRPC (and generated proto files) in combination with create-react-app, the eslint complain about all the generated proto JS code with the following error reported all over the shop:
`  Line 29:   'proto' is not defined  no-undef`

**Describe the solution you'd like**

Since I already have my own plugin to help generate some other things along with JS, it'd be nice to have access to insertion points for the top and bottom of the file, so I could add the following myself:

`/* eslint-disable */` and `/* eslint-enable */` respectively

**Describe alternatives you've considered**

Ana lternative would be to have an option in the compiler that would add those for me, for instance:

```
    protoc 
      --js_out="import_style=commonjs,disable_eslint=true,binary:$OUTPUT_PATH"
      ${currentProto}
```

**Comment by dibenede** [comment]
Sorry, we don't have plans to add insertion points support.
