### ISSUE TITLE
Failed to parse server response when using jstype = JS_STRING

### ISSUE THREAD

**Issue by sangaman** [protocolbuffers/protobuf-javascript#52]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: Javascript

**What operating system (Linux, Windows, ...) and version?**
Mac/Windows/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
Node v10.15.1 (as well as older versions)

**What did you do?**
Set `jstype = JS_STRING` on a `uint64` field within a response message definition. Make a grpc call that includes this field in the response.

**What did you expect to see**
A successful response.

**What did you see instead?**
An `INTERNAL` error of `failed to parse server response`.

**Anything else we should know about your project / environment**
This issue does not seem to be present in v3.4.0, downgrading makes the problem go away.

Related issue: https://github.com/grpc/grpc-node/issues/789

**Comment by dibenede** [comment]
It's hard to tell what the root cause is from the description, but this may be caused by trying to store a number as a string. This may have been already fixed since the types on the function have been adjusted.
