### ISSUE TITLE
[Enhancement] pre-built protoc binary via npm package

### ISSUE THREAD

**Issue by pumano** [protocolbuffers/protobuf-javascript#58]
**What language does this apply to?**
Javascript / TypeScript (via gRPC-web)
**Describe the problem you are trying to solve.**
We have (windows/mac/linux) developer laptops and want to have similar flow for downloading and using `protoc`. 
Looks like _making protoc from source code or downloading binaries from this repo_ **is not good solution** for distribution in 2018
**Describe the solution you'd like**
It's nice to have pre-built binaries installed via nodejs npm for using it. For example when I want to npm install `google-protobuf` npm package I also get pre-built binary for my platform (linux/windows/macosx) and use it via terminal
**Describe alternatives you've considered**
`choco` for windows / protoc via `make install`? / `homebrew` for mac os

**Comment by dibenede** [comment]
Duplicate of #29
