### ISSUE TITLE
both google protobuf npm and nuget package do not have LICENSE file

### ISSUE THREAD

**Issue by bpxlion** [protocolbuffers/protobuf-javascript#60]
Hi,

I install the google-protobuf npm package through "npm install google-protobuf". But I see there is no LICENSE file inside.

For the nuget package, it also does not have the LICENSE file.

May I know how to ask adding the LICENSE file into npm package? otherwise looks like hard to really consume the package :) 

Thank you very much.

**Comment by dibenede** [comment]
We have just published v3.21.1 of google-protobuf on NPM and it should now have the relevant license.
