### ISSUE TITLE
Is it possible to use 'import_style' for Typescript

### ISSUE THREAD

**Issue by wiewioraseb** [protocolbuffers/protobuf-javascript#69]
I want to have access to types when I get statically generated protobuff files. 

Running code: 
`protoc -I=Protos --js_out=import_style=es6,binary:Javascript Protos/MessageEvnelope.proto Protos/Messages.proto`

Generates .js files that are not easily imported in Typescript. When:
`import { SomeMessage } from './Messages_pb';`
I got error:

> Could not find a declaration file for module './Messages_pb' ... implicitly has an 'any' type.

To overcome this, I have to use `require('./Messages_pb')` which results with no types, which does not satisfy me. 

Is there an automatic way to create types for such generated js file? Or some other way to have types in typescript?

**Comment by dibenede** [comment]
Duplicate of #98
