### ISSUE TITLE
getJsPbMessageId() retrun ""

### ISSUE THREAD

**Issue by fengzhi09** [protocolbuffers/protobuf-javascript#72]
here is what i have done:

1. define a proto.file like this
```
syntax = "proto2";
message Awsome
{   
    required string  some_field   = 1;
}

```

2. compile proto with protoc.exe (version 3.5.1)  and get message_pb.js 

```
var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Awsome', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Awsome = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Awsome, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Awsome.displayName = 'proto.Awsome';
}
……
```
3. define a new message, and try to judge it's type in another method 
```
function doSomeWor(message) {
     // code 1
     if(message.getJsPbMessageId()=="Awsome "){
           // do something
     }

     // code 2
     if(message.displayName =="proto.Awsome "){
           // do something
     }
}
```
Unfortunately, both codes can not work，message.getJsPbMessageId() return “”  while message.displayName  return undefine
4.if i change the message_pb.js to this，code 1 will work

`  jspb.Message.initialize(this, opt_data,  'Awsome', -1, null, null);`

but i think you may do this automaticly when generating message_pb.js。 thank you

**Comment by dibenede** [comment]
getJsPbMessageId represents an internal only API that doesn't exist in open source. The function shouldn't exist at all.

displayName is intended as debug only.
