### ISSUE TITLE
[JS] toString on proto.google.protobuf.Int64Value doesn't return the correct value on large numbers

### ISSUE THREAD

**Issue by neurojab** [protocolbuffers/protobuf-javascript#74]
Create a proto.google.protobuf.Int64Value with the value 9223372036854775807

Call toString on it.  You'll get back 9223372036854776000

I'm sure it's converting it to a JS Number then converting it to a string, which is exactly what I don't want it to do.   

I'm also interested in any workarounds.

**Comment by dibenede** [comment]
Duplicate of #67 , #21
