### ISSUE TITLE
JS - How to get and set fields of inner message field 

### ISSUE THREAD

**Issue by jonathan-se** [protocolbuffers/protobuf-javascript#79]
Given the following message:
message A{
--  message B{
------  int32 x = 1
------  int32 y = 2
--  }
--  int32 foo = 1
--  B bar       = 2
}

msg = A.deserializeBinary(buffer)

1) Is msg.getBar().getX() is the only way to get x value? or there is a nicer solution like msg.bar.getX() (without using toObject())?

2) How can I set the value of x field without creating a new B message?

**Comment by dibenede** [comment]
Unfortunately with the current API users have to use a set*(new Foo()) pattern to create inner object fields.
