### ISSUE TITLE
JS - toObject() inconsistent behavior with empty fields

### ISSUE THREAD

**Issue by jonathan-se** [protocolbuffers/protobuf-javascript#80]
When a message contains an inner message field, if it's left empty, toObject() will return undefined for that field value and that Implies the field was empty in the original message.
But when the empty field is a Singular Scalar Field, toObject() will return default value for its type and it's not possible to know if this was the original value of the field or was it originally empty.

Probably the difference is derived from the same difference in getField(), but why not use hasFeild() to really determine if the field is empty and to set the value of it to "undefined" in all cases? otherwise it's not possible to trust and use the object representation.

**Comment by dibenede** [comment]
Proto3 doesn't have presence semantics by default. You need to add the `optional` keyword to get the desired behavior.

**Comment by mostafafarzaneh** [comment]
I have used optional in proto file but the generated file uses `jspb.Message.getFieldWithDefault(msg, 1, "")`, which is default to "" instead of undefined

**Comment by lukesandberg** [comment]
The best way to test for presence is to call the generated has-er method.

I agree that toObject() could work as described but we have found that
other users desire the current behavior and at this point changing would be
disruptive.

The toObject method is meant for convenience when working with other APIs
that need plain objects. It isn’t indented for interchange or to provide
full proto API fidelity.
