### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by sm2017** [protocolbuffers/protobuf-javascript#84]
I have a problem with JavaScript protobuf (version 3.4.0 ,  )

in the following code

```js
var message = MyMessage.deserializeBinary(bytesFromServer);
```

When I have  a `repeated uint64` field I have `Assertion failed` error, in other cases I have no problem

I know `bytesFromServer` is correct , other languages can deserialize the message

**Comment by dibenede** [comment]
Duplicate of #63 - packed repeated field issue
