### ISSUE TITLE
All bytes field parsing errors in the proto file in the JS version

### ISSUE THREAD

**Issue by zdccool** [protocolbuffers/protobuf-javascript#90]
When I define a field a in the proto file as a bytes type value of string, call serializeBinary and then call deserializeBinary, the value of jspb.Message.bytesAsB64 is incorrect 

i use syntax = "proto2";

**Comment by dibenede** [comment]
We will need more information to dig into this.

> I also have a similar problem. I load the data to base64 from the file, then run deserializeBinary(...). After that, I serialize it, getting Uint8Array at the output. I convert it to base64 and the result does not match the original value.

Protobuf serialization order isn't spec'd, so it's expected that the result may not match the original value.
