### ISSUE TITLE
Proto3 integration with JS

### ISSUE THREAD

**Issue by jayashreesantosh** [protocolbuffers/protobuf-javascript#91]
Hello Team,

I have used proto on java side successfully. 

However, now I need to use it for JS side or more specifically on the browser side. I am able to generate the proto_pb.js file for a proto3 source file. However, the steps mentioned in the below site does not work(tried the commonjs style), saying require is not supported for browsers and use browserify/webpack etc. When tried to use browserify it complained that module(proto_pb.js) not found. No luck yet.

https://github.com/google/protobuf/tree/master/js

Could you please share the complete steps for JS or browser side proto3 integration.

Thanks in advance

**Comment by dibenede** [comment]
The browser option is still a placeholder and unfinished. We expect users to use browserify/other bundlers if they are selecting commonjs.
